# Basic Java 21 configuration
image: gitpod/workspace-java-17

tasks:
  - init: |
      sdk install java 21.0.1-graal
      sdk default java 21.0.1-graal

# Optional: Install additional tools
tooling:
  java:
    image: gitpod/workspace-java-17
    env:
      JAVA_HOME: /home/gitpod/.sdkman/candidates/java/current

# VS Code Java extensions
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscjava.vscode-gradle
